# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU


ORACLE_USERNAME : "admin1"
ORACLE_PASSWORD : "1234"
GOOLE_AUTH_USER: '766695843300-cu1ji88lcq55m7cr3k3te4vkk76hjpe3.apps.googleusercontent.com'
GOOGLE_AUTH_KEY: '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'


